import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/app/auth/Provider"
import localFont from 'next/font/local'
import { Toaster } from 'react-hot-toast'

const bricolage = localFont({
  src: '../public/fonts/font.ttf',
  variable: '--font-custom'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bricolage.className}`}>
      <body
        className={`${bricolage.variable} ${bricolage.className} antialiased`}
      >
        <SessionProvider>
          {children}
          <Toaster position="top-center"
          toastOptions={{
            duration: 2000,
            success: {
              className:"bg-emerald-600 text-white border border-emerald-700 rounded-xl shadow-md"
            },
            error: {
              className:"bg-red-600 text-white border border-red-700 rounded-xl shadow-md"
            }
          }}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
